server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password: Root@200200
    driver-class-name: com.mysql.jdbc.Driver