server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:review;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

# Enable when you make sure a Kafka instance is up and running in the specific address
#kafka:
#  bootstrapAddress: 0.0.0.0:9092