###
# Acceptto Confidential
#
# This file is part of 'Atlas' module of the 'PAM' project.
#
# Copyright (c) 2017-2020 Acceptto Corporation All Rights Reserved.
#
# All information contained herein is, and remains the property
# of Acceptto Corporation.
# The intellectual and technical concepts contained herein are proprietary
# to Acceptto Corporation and covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
# Dissemination of this information or reproduction of this material
# is strictly forbidden unless prior written permission is obtained
# from Acceptto Corporation.
###

swagger: '2.0'
info:
  title: Review API
  version: "1.0.0"
  description: Review REST API documentation
host: localhost:8080
basePath: /api
schemes:
  - http
produces:
  - application/json
paths:
  /products:
    get:
      description:
        To list products
      tags:
        - Products
      parameters:
        - name: page
          in: query
          description: Page value.
          required: false
          type: number
          default: 0
        - name: size
          in: query
          description: Size of page.
          required: false
          type: number
          default: 10
      responses:
        200:
          description: A list of products returns
          schema:
            $ref: '#/definitions/ProductsListResponse'
        400:
          description: Request is invalid
        500:
          description: Internal server error.
  /products/{id}:
    put:
      tags:
        - Products
      description: Update a product's state, e.g., make it visible ,...
      parameters:
        - name: id
          in: path
          type: string
          required: true
          description: id of specific product
        - name: body
          in: body
          required: true
          description: body of edit request.
          schema:
            $ref: "#/definitions/EditProduct"
      responses:
        204:
          description: The operation was successful.
        400:
          description: Bad request, id is invalid.
        404:
          description: Requested object not found.
        500:
          description: Internal server error.

definitions:
  ProductsListResponse:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/ProductsList'

  ProductsList:
    type: object
    properties:
      id:
        type: number
        description: Identifier of the product.
      name:
        type: string
        description: Name of the product.
      is_visible:
        type: boolean
        description: Either if this product is visible to the users.
      is_commentable:
        type: boolean
        description: Either if this product is commentable to the users.
      is_commentable_to_pulic:
        type: boolean
        description: Indicates if this product is commentable to public or only the previous buyers can comment on.
      is_ratable:
        type: boolean
        description: Either if this product is ratable to the users.
      is_ratable_to_pulic:
        type: boolean
        description: Indicates if this product is ratable to public or only the previous buyers can rate on.

  EditProduct:
    type: object
    properties:
      is_visible:
        type: boolean
        description: Either if this product is visible to the users.
      is_commentable:
        type: boolean
        description: Either if this product is commentable to the users.
      is_commentable_to_pulic:
        type: boolean
        description: Indicates if this product is commentable to public or only the previous buyers can comment on.
      is_ratable:
        type: boolean
        description: Either if this product is ratable to the users.
      is_ratable_to_pulic:
        type: boolean
        description: Indicates if this product is ratable to public or only the previous buyers can rate on.